// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNree2fECtz2HFtwAKzw_gUQqORsz2hi0',
    appId: '1:221991541834:web:469329be45433538d09ab3',
    messagingSenderId: '221991541834',
    projectId: 'gt-intern-flutter2023',
    authDomain: 'gt-intern-flutter2023.firebaseapp.com',
    storageBucket: 'gt-intern-flutter2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKapfLm9bxRRwbwCuEVIdpoPd1J0APINU',
    appId: '1:221991541834:android:fb2cc3eac9c6f58cd09ab3',
    messagingSenderId: '221991541834',
    projectId: 'gt-intern-flutter2023',
    storageBucket: 'gt-intern-flutter2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgi8ZiEZiL-mGNIsbxgkjNlbc1EOSX0l4',
    appId: '1:221991541834:ios:c479c963ac9c494dd09ab3',
    messagingSenderId: '221991541834',
    projectId: 'gt-intern-flutter2023',
    storageBucket: 'gt-intern-flutter2023.appspot.com',
    iosClientId: '221991541834-i44nuthpvir8tfhj0us66tdlthifiq28.apps.googleusercontent.com',
    iosBundleId: 'com.example.countryStateCity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgi8ZiEZiL-mGNIsbxgkjNlbc1EOSX0l4',
    appId: '1:221991541834:ios:ab1879288329ca92d09ab3',
    messagingSenderId: '221991541834',
    projectId: 'gt-intern-flutter2023',
    storageBucket: 'gt-intern-flutter2023.appspot.com',
    iosClientId: '221991541834-j70dvjb68ha6se48s26bo6m8snj05alq.apps.googleusercontent.com',
    iosBundleId: 'com.example.countryStateCity.RunnerTests',
  );
}
